version: '3.5'
services:

  postgres1:
    container_name: eventr-pg1
    image: postgres:11-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password12!
      - POSTGRES_DB=eventr
    networks:
      - eventr_network

  postgres2:
    container_name: eventr-pg2
    image: postgres:11-alpine
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password12!
      - POSTGRES_DB=eventr
    networks:
      - eventr_network

  postgres3:
    container_name: eventr-pg3
    image: postgres:11-alpine
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password12!
      - POSTGRES_DB=eventr
    networks:
      - eventr_network

networks:
  eventr_network:
    name: eventr_network